"""initial schema

Revision ID: 8cb93939982a
Revises: 
Create Date: 2026-09-24 19:56:49.483361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8cb93939982a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broadcasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_tg_id', sa.BigInteger(), nullable=False),
    sa.Column('source_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('source_message_id', sa.Integer(), nullable=False),
    sa.Column('audience', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('sent', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('preview', sa.String(length=255), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('broadcasts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_broadcasts_admin_tg_id'), ['admin_tg_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_broadcasts_status'), ['status'], unique=False)

    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('ban_reason', sa.String(length=255), nullable=True),
    sa.Column('banned_at', sa.DateTime(), nullable=True),
    sa.Column('can_delete_messages', sa.Boolean(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chats_tg_id'), ['tg_id'], unique=True)

    op.create_table('platform_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('quality', sa.String(length=16), nullable=False),
    sa.Column('max_media_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('fetch_queue_size', sa.Integer(), nullable=False),
    sa.Column('fetch_concurrency', sa.Integer(), nullable=False),
    sa.Column('fetch_rate_per_second', sa.Float(), nullable=False),
    sa.Column('processing_queue_size', sa.Integer(), nullable=False),
    sa.Column('processing_concurrency', sa.Integer(), nullable=False),
    sa.Column('processing_max_ram_bytes', sa.BigInteger(), nullable=False),
    sa.Column('direct_url_video_limit', sa.BigInteger(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('platform_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platform_settings_platform'), ['platform'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('language_code', sa.String(length=16), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('ban_reason', sa.String(length=255), nullable=True),
    sa.Column('banned_at', sa.DateTime(), nullable=True),
    sa.Column('has_dm_access', sa.Boolean(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_tg_id'), ['tg_id'], unique=True)

    op.create_table('broadcast_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broadcast_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.String(length=255), nullable=True),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['broadcast_id'], ['broadcasts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('broadcast_targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_broadcast_targets_broadcast_id'), ['broadcast_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_broadcast_targets_tg_id'), ['tg_id'], unique=False)

    op.create_table('memberships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'chat_id', name='uq_membership')
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memberships_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_tg_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('admin_note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suggestions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_suggestions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_suggestions_user_tg_id'), ['user_tg_id'], unique=False)

    op.create_table('usage_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('user_tg_id', sa.BigInteger(), nullable=True),
    sa.Column('chat_tg_id', sa.BigInteger(), nullable=True),
    sa.Column('platform', sa.String(length=16), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('media_type', sa.String(length=24), nullable=True),
    sa.Column('media_group_type', sa.String(length=24), nullable=True),
    sa.Column('quality', sa.String(length=24), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('bytes_total', sa.BigInteger(), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.String(length=255), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_events_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_events_chat_tg_id'), ['chat_tg_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_events_outcome'), ['outcome'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_events_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_events_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_events_user_tg_id'), ['user_tg_id'], unique=False)
        batch_op.create_index('ix_usage_platform_created', ['platform', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usage_events', schema=None) as batch_op:
        batch_op.drop_index('ix_usage_platform_created')
        batch_op.drop_index(batch_op.f('ix_usage_events_user_tg_id'))
        batch_op.drop_index(batch_op.f('ix_usage_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_usage_events_platform'))
        batch_op.drop_index(batch_op.f('ix_usage_events_outcome'))
        batch_op.drop_index(batch_op.f('ix_usage_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_usage_events_chat_tg_id'))
        batch_op.drop_index(batch_op.f('ix_usage_events_chat_id'))

    op.drop_table('usage_events')
    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suggestions_user_tg_id'))
        batch_op.drop_index(batch_op.f('ix_suggestions_status'))
        batch_op.drop_index(batch_op.f('ix_suggestions_created_at'))

    op.drop_table('suggestions')
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_chat_id'))

    op.drop_table('memberships')
    with op.batch_alter_table('broadcast_targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_broadcast_targets_tg_id'))
        batch_op.drop_index(batch_op.f('ix_broadcast_targets_broadcast_id'))

    op.drop_table('broadcast_targets')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_tg_id'))

    op.drop_table('users')
    with op.batch_alter_table('platform_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platform_settings_platform'))

    op.drop_table('platform_settings')
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chats_tg_id'))

    op.drop_table('chats')
    with op.batch_alter_table('broadcasts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_broadcasts_status'))
        batch_op.drop_index(batch_op.f('ix_broadcasts_admin_tg_id'))

    op.drop_table('broadcasts')
    # ### end Alembic commands ###
