"""Shared foundation of the downloader SDKs.

``downloader.core`` holds everything that is identical across platforms:
the models, the HTTP layer, the ffmpeg bridge, the download engine, quality
selection and the disk saver. The platform packages (``reddit``, ``youtube``,
``twitter``) only add extraction logic - and, in Reddit's case, predate this
package and keep their own copy of these primitives.
"""

from .base import BaseClient
from .config import PlatformConfig
from .engine import DownloadEngine, DownloadOutcome
from .enums import (
    Container,
    DownloadTarget,
    FormatKind,
    FormatOrigin,
    MediaGroupType,
    MediaKind,
    Platform,
    StrEnum,
)
from .exceptions import (
    AuthenticationError,
    DownloadError,
    DownloaderError,
    InvalidURLError,
    MetadataError,
    MediaNotAvailableError,
    MuxingError,
    NoMediaError,
    PostNotFoundError,
    ProviderError,
    SaveError,
    SizeLimitExceededError,
    UnsupportedURLError,
)
from .http import HttpClient, HttpOptions, HttpResponse, StreamInfo, lowercase_headers
from .models import (
    DownloadResult,
    DownloadedFile,
    MediaFormat,
    MediaGroup,
    MediaItem,
    PostMetadata,
    Quality,
    Thumbnail,
    audio_container_matches,
    codec_matches,
    format_preference,
    group_items,
    human_size,
    parse_height,
    pick_audio,
    pick_format,
    quality_key,
    rank_formats,
)
from .progress import (
    MaybeAsyncProgress,
    ProgressCallback,
    ProgressEvent,
    ProgressPhase,
    emit,
)
from .select import (
    PlanEntry,
    QualitySpec,
    audio_candidates,
    build_plan,
    parse_quality,
    select_audio,
    select_still,
    select_video,
    video_candidates,
)
from .saver import album_directory, render_pattern, save_metadata, save_result
from .urls import (
    extension_of,
    filename_of,
    host_of,
    kind_for_extension,
    mime_for_extension,
)

__all__ = [
    "AuthenticationError",
    "BaseClient",
    "Container",
    "DownloadEngine",
    "DownloadError",
    "DownloadOutcome",
    "DownloadResult",
    "DownloadTarget",
    "DownloadedFile",
    "DownloaderError",
    "FormatKind",
    "FormatOrigin",
    "HttpClient",
    "HttpOptions",
    "HttpResponse",
    "InvalidURLError",
    "MaybeAsyncProgress",
    "MediaFormat",
    "MediaGroup",
    "MediaGroupType",
    "MediaItem",
    "MediaKind",
    "MediaNotAvailableError",
    "MetadataError",
    "MuxingError",
    "NoMediaError",
    "PlanEntry",
    "Platform",
    "PlatformConfig",
    "PostMetadata",
    "PostNotFoundError",
    "ProgressCallback",
    "ProgressEvent",
    "ProgressPhase",
    "ProviderError",
    "Quality",
    "QualitySpec",
    "SaveError",
    "SizeLimitExceededError",
    "StreamInfo",
    "StrEnum",
    "Thumbnail",
    "UnsupportedURLError",
    "album_directory",
    "audio_candidates",
    "audio_container_matches",
    "codec_matches",
    "format_preference",
    "build_plan",
    "emit",
    "extension_of",
    "filename_of",
    "group_items",
    "host_of",
    "human_size",
    "kind_for_extension",
    "lowercase_headers",
    "mime_for_extension",
    "parse_height",
    "parse_quality",
    "pick_audio",
    "pick_format",
    "quality_key",
    "rank_formats",
    "render_pattern",
    "save_metadata",
    "save_result",
    "select_audio",
    "select_still",
    "select_video",
    "video_candidates",
]